name: "CI"
on:
  - pull_request

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22.6'
      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build ios --debug --no-codesign
      - uses: actions/upload-artifact@v1
        with:
          name: release-ofa.apk
          path: build/app/outputs/apk/release/app-release.apk
      - uses: actions/upload-artifact@v1
        with:
          name: debug-ofa.app
          path: build/ios/iphoneos/Runner.app
